# Deliverfile
$app_identifier = "dynamic.school.orange"
$app_name = "orange"
$app_version = ""



# Define the app identifier
app_identifier($app_identifier)

# Define the username for App Store Connect
username("ios.dtechnp@gmail.com")


# Specify the build number (you can use variables or provide a static value)
build_number("1")


# Define metadata for different languages
metadata_path("./fastlane/metadata")

# Define screenshots path
screenshots_path("./fastlane/screenshots")

# Define app description and keywords for each language
description({
  'en-US' => "#{$app_name} School App is the comprehensive academic management solution designed for educational institutions, teachers, students, and parents. Streamline your daily activities and enhance your educational experience effortlessly!

  Features:
  
  For Teachers:
  
  Effortlessly manage attendance records with a tap.
  Simplify homework assignments, grading, and parent communication.
  Quickly input grades and comments for report cards.
  For Students:
  
  Submit homework assignments with ease.
  Stay updated on attendance and academic progress.
  Access report cards and track your educational journey.
  For Parents:
  
  Receive real-time attendance alerts for your child.
  Monitor homework assignments and grades effortlessly.
  Conveniently pay school fees and access fee summaries.
  For Non-Teaching Staff:
  
  Manage attendance and leave requests efficiently.
  Stay connected with colleagues and administrators.
  Streamline daily operations effortlessly.
  For the Public:
  
  Explore the institution without the need to log in. Discover:
  Upcoming events and past activities.
  Vision, mission, and admission procedures.
  Notices, academic programs, suggestions, facilities, and galleries.
  Holiday schedules for planning your visits.
  Key Benefits:
  
  Seamless communication: Stay connected with your educational community.
  Efficient task management: Simplify daily activities, from attendance to homework.
  Accessible information: Public access promotes transparency and engagement.
  Empower your education: Monitor progress and analyze student activities.
  User-friendly and secure: Your data is protected, and navigation is intuitive.
  Empower your educational journey with the Bal Sansar School App. Whether you are a teacher, student, parent, or part of the community, this app puts the institution at your fingertips. Download now and experience the future of academic management!"})

keywords({
  'en-US' => ['Academic Erp', 'Academic App' , 'Nepal Academic App' , $app_name , "#{$app_name} academic erp " ],
  
})

# Define additional metadata
promotional_text({
  'en-US' => 'All Academic Solution in One Place',

})

# Define support URL and marketing URL
support_url({
  'en-US' => 'https://dynamic.net.np/contact-us',

})

marketing_url({
  'en-US' => 'https://dynamic.net.np/contact-us'
 
})

privacy_url({
    'en-US' => 'https://dynamic.net.np/privacy-policy'
})

# Define app review information
app_review_information({
  contact_first_name: 'Rukesh',
  contact_last_name: 'Gwachha',
  contact_phone: '+9779860918184',
  contact_email: 'rukeshgwachha@gmail.com',
  demo_account_name: 'adminuat',
  demo_account_password: 'adminuat@2020',
  demo_account_instructions: 'Login and test the app'
})

# Define app pricing and availability
# price_tier(0)
# availability({
#   'en-US' => 'Available on the App Store',

# })

# Define app rating information
# rating_config_path('./fastlane/rating_config.json')

# Define review notes for the app submission
# review_notes({
#   'en-US' => 'Release notes in English',
#   'fr-FR' => 'Notes de version en français'
# })
