lane :createapp do
    create_app_online
  end
  
  
  
  platform :ios do
    
    lane :signing do
      sync_code_signing
      mapping = Actions.lane_context[
        SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
      ]
      update_code_signing_settings(
        profile_name: mapping[ENV["MATCH_APP_IDENTIFIER"]]
      )
    end
  
    lane :build do
      signing
    
    end
    lane :release do
      gym(scheme: "mango", export_method: "app-store")
      match(type: "appstore")
     
    end
  end
